version: "2.2"
services:
  asir_bind9:
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 53:53
    volumes:
      - dns_conf:/etc/bind
  asir_cliente:
    image: cliente_ubuntu:net-tools
    dns:
    - 172.18.0.3
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
volumes:
  dns_conf:
    external: true